### ISSUE TITLE
Problems with `stack` on run(model)

### ISSUE THREAD

**Issue by jrising** [rffscghg/MimiRFFSPs.jl#39]
I am working with a PhD student, and on her machine the MimiGIVE model does not run because of an error from MimiRFFSPs. The error claims that `stack` is exported by Base. I think this comes from the new version of Julia, because I don't think my Base includes a stack function. Here's the error:

```
WARNING: both DataFrames and Base export "stack"; uses of it in module MimiRFFSPs must be qualified
ERROR: UndefVarError: `stack` not defined
Stacktrace:
  [1] (::MimiRFFSPs.var"#3#7")(i::DataFrames.DataFrame)
    @ MimiRFFSPs C:\Users\Deepak\.julia\packages\MimiRFFSPs\J6wRq\src\components\SPs.jl:153
  [2] |>
    @ .\operators.jl:907 [inlined]
...
```

Are there version limits with MimiRFFSPs?

**Comment by lrennels** [comment]
Hi @jrising so sorry for the delay on this, I haven't run into this problem and am on Julia 1.8, is she on 1.9?  RIght now I believe the combat for MimiRFFSPs and MimiGIVE does say Julia 1.6, but I would plan to bump that up since it should certainly be made available on newer versions.  @davidanthoff and I will look into this and get back to you quickly.

**Comment by lrennels** [comment]
I did see this is in Julia 1.9 so that's probably what's going on here.

```
New function stack(x) which generalises reduce(hcat, x::Vector{<:Vector}) to any dimensionality, and allows any iterator of iterators. Method stack(f, x) generalises mapreduce(f, hcat, x) and is more efficient ([#43334](https://github.com/JuliaLang/julia/issues/43334)).
```

**Comment by lrennels** [comment]
@jrising I think this PR should help https://github.com/rffscghg/MimiRFFSPs.jl/pull/40 unless you have a more clever way to prioritize the DataFrames `stack` function over `Julia`. I can merge it and then `MimiGIVE` should pull in the new version.

**Comment by jrising** [comment]
@lrennels Your PR looks like it does just what's needed. Thanks.

**Comment by lrennels** [comment]
Great thank you @jrising just one of the 15 test configurations are failing right now, likely due to some CI issue but I'm going to wait until those go through before merging

**Comment by lrennels** [comment]
Done #40 and tagging new version (patch) v1.1.1
